export const MODULE_CATEGORY_SLUG: Record<string, string> = {
  g1: "driving-licensing",
  "javascript-1": "programming-languages",
  "javascript-2": "programming-languages",
  "javascript-3": "programming-languages",
  "typescript-1": "programming-languages",
  "typescript-2": "programming-languages",
  "typescript-3": "programming-languages",
  "python-1": "programming-languages",
  "python-2": "programming-languages",
  "python-3": "programming-languages",
  "c-1": "programming-languages",
  "c-2": "programming-languages",
  "c-3": "programming-languages",
  "cpp-1": "programming-languages",
  "cpp-2": "programming-languages",
  "cpp-3": "programming-languages",
  "java-1": "programming-languages",
  "java-2": "programming-languages",
  "java-3": "programming-languages",
  "csharp-1": "programming-languages",
  "csharp-2": "programming-languages",
  "csharp-3": "programming-languages",
  "sql-1": "programming-languages",
  "sql-2": "programming-languages",
  "sql-3": "programming-languages",
  "go-1": "programming-languages",
  "go-2": "programming-languages",
  "go-3": "programming-languages",
  "rust-1": "programming-languages",
  "rust-2": "programming-languages",
  "rust-3": "programming-languages",
  "real-estate": "test-prep",
  english: "languages",
  spanish: "languages",
  french: "languages",
  japanese: "languages",
  italian: "languages",
  portuguese: "languages",
};

export const DEFAULT_CATEGORY_SLUG = "other";

export function categoryForModule(moduleSlug: string): string {
  return MODULE_CATEGORY_SLUG[moduleSlug] ?? DEFAULT_CATEGORY_SLUG;
}
